services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: library_postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_user -d library_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Book Service
  book-service:
    build:
      context: .
      dockerfile: book-service/Dockerfile
    container_name: library_book_service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library_db
      - SPRING_DATASOURCE_USERNAME=library_user
      - SPRING_DATASOURCE_PASSWORD=library_password
      - GRPC_SERVER_PORT=9091
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
      - "9091:9091"
    networks:
      - library-network
    depends_on:
      postgres:
        condition: service_healthy

  # User Service
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: library_user_service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library_db
      - SPRING_DATASOURCE_USERNAME=library_user
      - SPRING_DATASOURCE_PASSWORD=library_password
      - GRPC_SERVER_PORT=9093
      - SERVER_PORT=8082
    ports:
      - "8082:8082"
      - "9093:9093"
    networks:
      - library-network
    depends_on:
      postgres:
        condition: service_healthy

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: library_api_gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BOOK_SERVICE_HOST=book-service
      - BOOK_SERVICE_PORT=9091
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=9093
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - library-network
    depends_on:
      book-service:
        condition: service_started
      user-service:
        condition: service_started

volumes:
  postgres_data:
    driver: local

networks:
  library-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16