server:
  port: 9091

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

grpc:
  server:
    port: 6566
  client:
    GLOBAL:
      negotiationType: plaintext

logging:
  level:
    com.library.userservice: DEBUG
    org.springframework.data: DEBUG
    org.hibernate: DEBUG